/**
 * Created by 马荣钦 on 2016/1/21.
 */
angular.module("myZonePersonalInfoRouterModule",[])
    .config(['$stateProvider',function($stateProvider){
        $stateProvider.state("myzone.personalinfo",{
            url:"/personalinfo",
            views:{
                'main@myzone':{
                    templateUrl:"./myZone/personalInfo/index_tpl.html",
                    controller:"myZonePersonalInfoCtrl"
                },
                "left@myzone.personalinfo":{
                    templateUrl:"./myZone/personalInfo/left_tpl.html",
                    controller:"myZonePersonalInfoLeftCtrl"
                },
                "footer@myzone.personalinfo":{
                    templateUrl:"./footer_tpl.html"
                }
            }
        })
            .state("myzone.personalinfo.info",{
                url:"/personalinfoinfo",
                views:{
                    'main@myzone.personalinfo':{
                        templateUrl:"./myZone/personalInfo/info/info_tpl.html",
                        controller:"myZonePerInfoInfoCtrl"
                    }
                }
            })
            .state("myzone.personalinfo.changepwd",{
                url:"/changepwd",
                views:{
                    'main@myzone.personalinfo':{
                        templateUrl:"./myZone/personalInfo/changePassword/changePassword_tpl.html",
                        controller:"myZonePerInfoChangePwdCtrl"
                    }
                }
            })
            .state("myzone.personalinfo.persetting",{
                url:"/personalsetting",
                views:{
                    'main@myzone.personalinfo':{
                        templateUrl:"./myZone/personalInfo/personalSetting/personalSetting_tpl.html",
                        controller:"myZonePerInfoPerSettingCtrl"
                    }
                }
            })
    }]);