"use strict";
angular.module('initAddMetaDataModule', []).
factory('initAddMetaDataService', ['$stateParams', 'editingCenterAppService', function($stateParams, editingCenterAppService) {
    return {
        initNews: function() {
            var list = {
                "METADATAID": 0,
                "CHANNELID": $stateParams.channelid,
                "LISTSTYLE": 0,
                "LISTTITLE": [],
                "LISTPICS": [],
                "LABEL": angular.copy(editingCenterAppService.initLabel()[0].value),
                "ISFOCUSIMAGE": 1,
                "FOCUSIMAGE": [],
                "NEWSSTYLE": "",
                "TITLE": "",
                "HTMLCONTENT": "",
                "CONTENT": "",
                "NEWSSOURCES": "",
                "CONTRIBUTORSAUTHER": "",
                "CONTRIBUTORSONE": angular.copy(editingCenterAppService.initContributorsOne()[0]),
                "CONTRIBUTORSTWO": angular.copy(editingCenterAppService.initContributorsOne()[0]),
                "CONTRIBUTORSTHREE": angular.copy(editingCenterAppService.initContributorsOne()[0]),
                "SIGNATUREAUTHOR": "",
                "KEYWORDS": "",
                "CONABSTRACT": "",
                "ISSELECTFIGURE": 0,
                "FIGURE": [],
                "COMMENTSET": 1,
                "BELONGCHANNEL": angular.copy(editingCenterAppService.initBelongChannel()[0]),
                "RELEVANTNEWSIDS": "",
                "RELEVANTOFFICIALSIDS": "",
                "ISNOPAYMENT": 1,
                "DOCGENRE": angular.copy(editingCenterAppService.initDocGenre()[0]),
                "FOCUSIMGTITLE": "",
                "DOCWORDSCOUNT": 0,
                "FGD_EDITINFO": [],
                "FGD_AUTHINFO": [{ "isCreate": true }],
            };
            return list;
        },
        initAtlas: function() {
            var list = {
                "CHANNELID": $stateParams.channelid,
                "METADATAID": 0,
                "LISTSTYLE": 0,
                "LISTPICS": [],
                "LABEL": angular.copy(editingCenterAppService.initLabel()[0].value),
                "ISFOCUSIMAGE": 1,
                "FOCUSIMAGE": [],
                "RELEASESOURCE": "",
                "SUBTITLE": "",
                "LEADTITLE": "",
                "NEWSSOURCES": "",
                "TEMPLATESETTING": "",
                "SIGNATUREAUTHOR": "",
                "CONTRIBUTORSAUTHER": "",
                "CONTRIBUTORSONE": angular.copy(editingCenterAppService.initContributorsOne()[0]),
                "CONTRIBUTORSTWO": angular.copy(editingCenterAppService.initContributorsOne()[0]),
                "CONTRIBUTORSTHREE": angular.copy(editingCenterAppService.initContributorsOne()[0]),
                "KEYWORDS": "",
                "CONABSTRACT": "",
                "ISSELECTFIGURE": "",
                "FOCUSIMGTITLE": "",
                "FIGURE": [],
                "COMMENTSET": 1,
                "DOC_PICTURELIST": [],
                "ISNOPAYMENT": 1,
                "DOCGENRE": angular.copy(editingCenterAppService.initDocGenre()[0]),
                "BELONGCHANNEL": angular.copy(editingCenterAppService.initBelongChannel()[0]),
                "FLOWVERSIONTIME": "",
                "DOCTYPE": "",
                "DOCWORDSCOUNT": 0,
                "FGD_EDITINFO": [],
                "FGD_AUTHINFO": [{ "isCreate": true }],
            };
            return list;
        },
        initSubject: function() {
            var list = {
                "CHANNELID": $stateParams.channelid,
                "METADATAID": 0,
                "LISTSTYLE": 0,
                "LISTTITLE": [],
                "LISTPICS": [],
                "LABEL": angular.copy(editingCenterAppService.initLabel()[0].value),
                "DISPLAYSET": 0,
                "TITLE": "",
                "FOCUSIMGTITLE": "",
                "ISFOCUSIMAGE": 1,
                "FOCUSIMAGE": [],
                "KEYWORDS": "",
                "CONABSTRACT": "",
                "ISSELECTFIGURE": 0,
                "FIGURE": [],
                "DOCWORDSCOUNT": 0,
                "FZ_SPECIALGROUPINFO": "",
            };
            return list;
        },
        initWebsite: function() {
            var list = {
                METADATAID: 0,
                CHANNELID: $stateParams.channelid,
                LISTSTYLE: 0,
                LISTTITLE: "",
                LISTPICS: [],
                LABEL: angular.copy(editingCenterAppService.initLabel()[0].value),
                BELONGCHANNEL: angular.copy(editingCenterAppService.initBelongChannel()[0]),
                ISFOCUSIMAGE: 1,
                FOCUSIMAGE: [],
                URL: "",
                COMMENTSET: 1,
                DOCWORDSCOUNT: 0,
                FOCUSIMGTITLE: "",
            };
            return list;
        },
    };
}]);
